name: .NET Core Build and Run

on:
  push:
    branches:
        - main
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run
        run: dotnet run 
        
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Create Issue on Failure
        if: failure()
        uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
